# Generated by Django 5.1.3 on 2025-02-20 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0048_alter_hotel_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('booked', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='hotels.booked')),
            ],
        ),
    ]
