# Generated by Django 5.1.3 on 2025-02-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_checkout_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
