# Generated by Django 5.1.3 on 2025-02-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
