# Generated by Django 5.1.3 on 2025-02-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='is_paid',
        ),
    ]
