# Generated by Django 5.1.3 on 2025-02-15 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0044_booked_is_paid'),
        ('payment', '0007_remove_checkout_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='in_date',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='out_date',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='room',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='checkout',
            name='booked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='hotels.booked'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
