# Generated by Django 5.1.3 on 2024-12-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='district',
            new_name='district_name',
        ),
    ]
