# Generated by Django 5.1.3 on 2024-12-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_rename_district_name_hotel_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='name',
            new_name='hotel_name',
        ),
    ]
