# Generated by Django 5.1.3 on 2024-12-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_remove_review_hotel_alter_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
