# Generated by Django 5.1.3 on 2024-12-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_rename_district_hotel_district_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='district_name',
            new_name='district',
        ),
    ]
