# Generated by Django 5.1.3 on 2024-12-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_rename_district_name_hotel_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='district',
            new_name='district_name',
        ),
    ]
