# Generated by Django 5.1.3 on 2024-12-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_rename_district_hotel_district_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.PositiveIntegerField()),
                ('in_date', models.DateField()),
                ('out_date', models.DateField()),
                ('payment', models.CharField(choices=[('ssl', 'ssl'), ('Account', 'Account')], max_length=10)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
    ]
