# Generated by Django 5.1.3 on 2024-12-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='district_name',
        ),
        migrations.AddField(
            model_name='hotel',
            name='ddistrict_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.district'),
        ),
    ]
