# Generated by Django 5.1.3 on 2024-12-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_remove_hotel_district_name_hotel_ddistrict_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='ddistrict_name',
            new_name='district_name',
        ),
    ]
