# Generated by Django 5.1.3 on 2024-12-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_rename_ddistrict_name_hotel_district_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='district_name',
            new_name='district_names',
        ),
    ]
