# Generated by Django 5.1.3 on 2025-01-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_remove_review_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='district_names',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='image',
            new_name='photo',
        ),
    ]
