# Generated by Django 5.1.3 on 2025-01-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_rename_district_names_hotel_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='district',
            new_name='district_names',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='name',
            new_name='hotel_name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='photo',
            new_name='image',
        ),
    ]
