# Generated by Django 5.1.3 on 2025-01-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_rename_district_hotel_district_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
    ]
