# Generated by Django 5.1.3 on 2025-01-07 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_alter_booked_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel'),
        ),
    ]
