# Generated by Django 5.1.6 on 2025-02-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0027_alter_booked_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
