# Generated by Django 5.1.3 on 2025-02-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0037_alter_booked_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='is_paid',
        ),
    ]
