# Generated by Django 5.1.3 on 2025-02-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0038_remove_booked_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
