# Generated by Django 5.1.3 on 2025-02-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0041_alter_booked_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
