# Generated by Django 5.1.3 on 2025-02-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0045_alter_review_rating_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
