# Generated by Django 5.1.3 on 2025-02-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0047_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
