# Generated by Django 5.1.3 on 2024-12-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
